modLoader="javafml" #mandatory

loaderVersion="[34,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="kunziteaccessories" #mandatory

version="${1.16.3-0.1.2}" #mandatory

displayName="Kunzite Accessories" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="https://discord.com/invite/362Yf9x" #optional

logoFile="kunzitelogo.png" #optional

credits="Thanks to you for using my mod!" #optional

authors="IWonByDefault" #optional

description='''A mod focused on a new resource - Kunzite! This rare gem has many uses, the primary focus being powerful accessories!'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.kunziteaccessories]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[34,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.kunziteaccessories]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
[[dependencies.kunziteaccessories]]
modId="curios"
mandatory=true
versionRange="[1.16.3-4.0.2.0]"
ordering="NONE"
side="BOTH"